'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const companies=['فايز المحيا للتجارة','أنيستيزيا'],branches=['الرياض — الفرع 1','الرياض — الفرع 2','الرياض — الفرع 3','حفر الباطن'];
const dateAfter=n=>{const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const seed=()=>({employees:[{id:'1001',name:'سارة أحمد',company:companies[0],branch:branches[0],dept:'التسويق',job:'أخصائية تسويق',mode:'مكتبي',manager:'مدير التسويق'},{id:'1002',name:'محمد خالد',company:companies[1],branch:branches[1],dept:'المبيعات',job:'مندوب مبيعات',mode:'ميداني',manager:'مشرف المبيعات'},{id:'1003',name:'عبدالله علي',company:companies[0],branch:branches[3],dept:'المبيعات',job:'مشرف مبيعات',mode:'ميداني',manager:'المدير التنفيذي'}],leaves:[{id:'l1',employee:'سارة أحمد',type:'سنوية',start:dateAfter(5),end:dateAfter(8),created:Date.now()-52*3600000,status:'بانتظار الاعتماد'},{id:'l2',employee:'محمد خالد',type:'سنوية',start:dateAfter(12),end:dateAfter(15),created:Date.now(),status:'بانتظار الاعتماد'}],docs:[{id:'d1',name:'رخصة تجارية — الرياض',company:companies[0],kind:'رخصة تجارية',number:'DEMO-01',expiry:dateAfter(24),notes:'بيانات تجريبية'},{id:'d2',name:'عقد إيجار — حفر الباطن',company:companies[1],kind:'عقد',number:'DEMO-02',expiry:dateAfter(58),notes:''}],cars:[{id:'c1',plate:'تجريبي 101',company:companies[0],holder:'عبدالله علي',registration:dateAfter(150),insurance:dateAfter(6),inspection:dateAfter(-3)}],sales:[{id:'s1',supervisor:'عبدالله علي',company:companies[0],period:dateAfter(0).slice(0,7),target:120000,actual:86500},{id:'s2',supervisor:'مشرف أنيستيزيا',company:companies[1],period:dateAfter(0).slice(0,7),target:100000,actual:73000}],tasks:[{id:'t1',title:'إعداد خطة محتوى FOREVER52',assignee:'سارة أحمد',due:dateAfter(3),status:'قيد التنفيذ'},{id:'t2',title:'تجهيز تقرير الحملة الأسبوعي',assignee:'سارة أحمد',due:dateAfter(5),status:'جديدة'}]});
const KEY='group-demo-v1';let db;try{db=JSON.parse(localStorage.getItem(KEY));if(!db||!['employees','leaves','docs','cars','sales','tasks'].every(k=>Array.isArray(db[k])))db=seed();}catch{db=seed();}
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));return true;}catch{toast('تعذر الحفظ في المتصفح. التغييرات متاحة لهذه الجلسة فقط.');return false;}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',3500);}
const pages={overview:['نظرة عامة','متابعة يومية للموظفين والطلبات وما يحتاج اهتمامك.','＋ إضافة موظف'],employees:['الموظفون','ملفات فريقك موزعة حسب الشركة والفرع والإدارة.','＋ إضافة موظف'],leaves:['الإجازات','طلبات الموظفين وتسلسل الاعتماد والتصعيد.','＋ طلب إجازة'],docs:['الوثائق والأصول','العقود والرخص ومواعيد التجديد الخاصة بإدارتك.','＋ إضافة وثيقة'],cars:['السيارات','متابعة العهد ووثائق المركبات كلٌّ على حدة.','＋ إضافة سيارة'],sales:['المبيعات','الأهداف والإنجاز لكل مشرف وشركة.','＋ إضافة سجل'],tasks:['مهام التسويق','توزيع العمل ومتابعة التسليم والإنجاز.','＋ إضافة مهمة']};
let page='overview';const icons=['◫','♙','▤','▣','◇','↗','☷'];
$('#nav').innerHTML=Object.entries(pages).map(([k,v],i)=>`<a href="#${k}" data-page="${k}"><span class="nav-icon">${icons[i]}</span>${v[0]}</a>`).join('');
$('#today').textContent=new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',calendar:'gregory'}).format(new Date());
const badge=(t,c='')=>`<span class="badge ${c}">${esc(t)}</span>`;
const days=d=>d?Math.round((Date.parse(d+'T00:00:00Z')-Date.parse(dateAfter(0)+'T00:00:00Z'))/86400000):null;
function expiry(d){let n=days(d);return n===null?badge('بلا تاريخ انتهاء'):n<0?badge(`منتهي منذ ${-n} يوم`,'bad'):n<=60?badge(n===0?'ينتهي اليوم':`متبقي ${n} يوم`,'warn'):badge('ساري','good');}
const escalated=l=>l.status==='بانتظار الاعتماد'&&Date.now()-l.created>=48*3600000;
const alerts=()=>[...db.docs.map(d=>({name:d.name,expiry:d.expiry,company:d.company})),...db.cars.flatMap(c=>[['الاستمارة','registration'],['التأمين','insurance'],['الفحص','inspection']].map(([n,k])=>({name:`${n} · ${c.plate}`,expiry:c[k],company:c.company})))].filter(d=>days(d.expiry)!==null&&days(d.expiry)<=60).sort((a,b)=>a.expiry.localeCompare(b.expiry));
const panel=(title,body,link='')=>`<div class="panel"><div class="panel-head"><h2>${title}</h2>${link}</div>${body}</div>`;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">لا توجد سجلات مطابقة.</td></tr>`}</tbody></table></div>`;
const stat=(label,value,sub)=>`<div class="stat"><span class="stat-label">${label}</span><strong>${value}</strong><small>${sub}</small></div>`;
function render(){page=location.hash.slice(1);if(!pages[page])page='overview';let p=pages[page];$('#title').textContent=p[0];$('#breadcrumb').textContent=p[0];$('#subtitle').textContent=p[1];$('#primary').textContent=p[2];document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);a.setAttribute('aria-current',a.dataset.page===page?'page':'false');});let out='';
if(page==='overview'){let a=alerts(),pending=db.leaves.filter(l=>l.status==='بانتظار الاعتماد');out=`<div class="stats">${stat('الموظفون في التجربة',db.employees.length,'الحجم المخطط: نحو 50 موظفًا')}${stat('طلبات تنتظر الاعتماد',pending.length,`${pending.filter(escalated).length} تجاوزت مهلة اليومين`)}${stat('وثائق تحتاج متابعة',a.length,'تشمل وثائق السيارات')}${stat('الفروع',4,'3 الرياض · 1 حفر الباطن')}</div><div class="grid">${panel('طلبات الإجازة',leaveTable(db.leaves.slice(0,4)),'<a href="#leaves">كل الطلبات ←</a>')}${panel('مواعيد قريبة',`<div class="panel-body">${a.map(d=>`<div class="row"><div>${esc(d.name)}<small>${esc(d.company)} · ${esc(d.expiry)}</small></div>${expiry(d.expiry)}</div>`).join('')||'<p class="empty">لا توجد مواعيد قريبة</p>'}</div>`,'<a href="#docs">الوثائق ←</a>')}</div>${panel('شركات المجموعة',`<div class="panel-body"><div class="row"><div><h2>شركة فايز المحيا للتجارة</h2><small>FOREVER52</small></div>${badge('ضمن المجموعة')}</div><div class="row"><div><h2>شركة أنيستيزيا</h2><small>ANESTHESI DREAM</small></div>${badge('ضمن المجموعة')}</div></div>`)}`;}
if(page==='employees')out=`<div class="toolbar"><input id="search" aria-label="بحث الموظفين" placeholder="ابحث بالاسم أو الرقم الوظيفي…"><select id="company-filter" aria-label="تصفية الشركة"><option value="">كل الشركات</option>${companies.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="panel" id="employee-list"></div>`;
if(page==='leaves')out=`<div class="notice">تظهر الطلبات المتأخرة بعد 48 ساعة لدى المدير الأعلى / المالك في هذه المحاكاة. التشغيل الفعلي والتصعيد الآلي يتطلبان ربط الخادم.</div>${panel('سجل الطلبات',leaveTable(db.leaves))}`;
if(page==='docs')out=`<div class="notice">قسمك الخاص في التصميم النهائي. النسخة الحالية محلية بلا حماية حسابات؛ استخدم بيانات تجريبية فقط. مواعيد التنبيه المقترحة: 60، 30، 7 أيام ويوم الانتهاء.</div>${panel('العقود والرخص والوثائق',table(['الوثيقة','الشركة','النوع','الانتهاء','الحالة','إجراء'],db.docs.map(d=>`<tr><td>${esc(d.name)}<br><small class="muted">${esc(d.number)}</small></td><td>${esc(d.company)}</td><td>${esc(d.kind)}</td><td>${esc(d.expiry||'—')}</td><td>${expiry(d.expiry)}</td><td><button class="action" data-renew="${esc(d.id)}">تجديد</button></td></tr>`)))}`;
if(page==='cars')out=panel('سجل المركبات',table(['اللوحة / المستلم','الشركة','الاستمارة','التأمين','الفحص'],db.cars.map(c=>`<tr><td>${esc(c.plate)}<br><small>${esc(c.holder)}</small></td><td>${esc(c.company)}</td>${['registration','insurance','inspection'].map(k=>`<td>${esc(c[k]||'—')}<br>${expiry(c[k])}</td>`).join('')}</tr>`)));
if(page==='sales')out=`<div class="notice">سجلات تجريبية يدوية لكل شهر، وليست متصلة بنظام المبيعات.</div><div class="task-grid">${db.sales.map(s=>`<article class="task">${badge(s.period)}<h2>${esc(s.supervisor)}</h2><p>${esc(s.company)}</p><strong>${Number(s.actual).toLocaleString('ar-SA')} ر.س</strong><p>من هدف ${Number(s.target).toLocaleString('ar-SA')} ر.س</p><div class="progress"><span style="width:${Math.min(100,s.actual/s.target*100)}%"></span></div><div class="row"><span>نسبة الإنجاز</span><b>${Math.round(s.actual/s.target*100)}%</b></div></article>`).join('')}</div>`;
if(page==='tasks')out=`<div class="task-grid">${db.tasks.map(t=>`<article class="task">${badge(t.status,t.status==='مكتملة'?'good':'')}<h2>${esc(t.title)}</h2><p>المسؤول: ${esc(t.assignee)}</p><p>موعد التسليم: ${esc(t.due)}</p>${t.status!=='مكتملة'?`<button class="action" data-task="${esc(t.id)}">${t.status==='جديدة'?'بدء التنفيذ':'تحديد كمكتملة'}</button>`:badge('تم الإنجاز','good')}</article>`).join('')||'<p class="empty">لا توجد مهام</p>'}</div>`;
$('#content').innerHTML=out;if(page==='employees'){employeeList();$('#search').oninput=employeeList;$('#company-filter').onchange=employeeList;}}
function employeeList(){let q=$('#search').value.trim(),c=$('#company-filter').value;$('#employee-list').innerHTML=table(['الموظف','الشركة / الفرع','الإدارة','العمل','المدير المباشر'],db.employees.filter(e=>(!q||(e.name+' '+e.id).includes(q))&&(!c||e.company===c)).map(e=>`<tr><td><b>${esc(e.name)}</b><br><span class="muted">${esc(e.id)} · ${esc(e.job)}</span></td><td>${esc(e.company)}<br><span class="muted">${esc(e.branch)}</span></td><td>${esc(e.dept)}</td><td>${badge(e.mode)}</td><td>${esc(e.manager)}</td></tr>`));}
function leaveTable(ls){return table(['الموظف / الفترة','الحالة','القرار'],ls.map(l=>`<tr><td>${esc(l.employee)}<br><small class="muted">${esc(l.start)} ← ${esc(l.end)} · ${esc(l.type)}</small></td><td>${badge(escalated(l)?'مصعّد للمدير الأعلى':l.status,l.status==='مقبولة'?'good':l.status==='مرفوضة'?'bad':'warn')}</td><td>${l.status==='بانتظار الاعتماد'?`<button class="action" data-leave="${esc(l.id)}" data-decision="مقبولة">قبول تجريبي</button><button class="action danger" data-leave="${esc(l.id)}" data-decision="مرفوضة">رفض</button>`:'—'}</td></tr>`));}
const field=(name,label,type='text',opts=null,required=true)=>({name,label,type,opts,required});
const company=()=>field('company','الشركة','select',companies);
function openForm(kind,id){let fields=[],title='',initial={};if(kind==='employees'){title='إضافة موظف تجريبي';fields=[field('id','الرقم الوظيفي'),field('name','اسم الموظف'),company(),field('branch','الفرع','select',branches),field('dept','الإدارة','select',['الموارد البشرية','المبيعات','التسويق','المالية','المستودعات','التطوير','الإدارة العامة']),field('job','المسمى الوظيفي'),field('mode','نمط العمل','select',['مكتبي','ميداني']),field('manager','المدير المباشر')];}
if(kind==='leaves'){if(!db.employees.length)return toast('أضف موظفًا أولًا');title='طلب إجازة تجريبي';fields=[field('employee','الموظف','select',db.employees.map(e=>e.name)),field('type','نوع الإجازة','select',['سنوية','مرضية','اضطرارية']),field('start','من تاريخ','date'),field('end','إلى تاريخ','date')];}
if(kind==='docs'){title='إضافة وثيقة';fields=[field('name','اسم الوثيقة'),company(),field('kind','النوع','select',['عقد','رخصة تجارية','سجل تجاري','أخرى']),field('number','رقم الوثيقة','text',null,false),field('expiry','تاريخ الانتهاء (اختياري)','date',null,false),field('notes','ملاحظات','text',null,false)];}
if(kind==='renew'){title='تجديد الوثيقة';initial=db.docs.find(d=>d.id===id);fields=[field('expiry','تاريخ الانتهاء الجديد','date')];}
if(kind==='cars'){title='إضافة سيارة';fields=[field('plate','رقم اللوحة'),company(),field('holder','الموظف المستلم'),...['registration','insurance','inspection'].map((k,i)=>field(k,['انتهاء الاستمارة','انتهاء التأمين','انتهاء الفحص'][i],'date',null,false))];}
if(kind==='sales'){title='إضافة سجل مبيعات';fields=[field('supervisor','المشرف'),company(),field('period','الشهر','month'),field('target','الهدف بالريال','number'),field('actual','المبيعات بالريال','number')];}
if(kind==='tasks'){title='إضافة مهمة تسويق';fields=[field('title','المهمة'),field('assignee','الموظف المسؤول'),field('due','موعد التسليم','date')];}
$('#dialog-title').textContent=title;$('#form-error').textContent='';$('#fields').innerHTML=fields.map(f=>`<label>${f.label}${f.type==='select'?`<select name="${f.name}">${f.opts.map(o=>`<option>${esc(o)}</option>`).join('')}</select>`:`<input name="${f.name}" type="${f.type}" value="${esc(initial[f.name]||'')}" ${f.required?'required':''} ${f.type==='number'?'min="0" step="0.01"':''} maxlength="200">`}</label>`).join('');
$('#form').onsubmit=async e=>{e.preventDefault();if(window.serverSaveBusy)return;let v=Object.fromEntries(new FormData(e.target));Object.keys(v).forEach(k=>v[k]=v[k].trim());let error=fields.some(f=>f.required&&!v[f.name])?'أكمل الحقول المطلوبة.':'';if(kind==='employees'&&db.employees.some(x=>x.id===v.id))error='الرقم الوظيفي موجود بالفعل.';if(kind==='leaves'&&v.end<v.start)error='تاريخ النهاية يجب ألا يسبق البداية.';if(kind==='sales'&&(!(Number(v.target)>0)||Number(v.actual)<0))error='الهدف يجب أن يكون أكبر من صفر والمبيعات غير سالبة.';if(kind==='renew'&&v.expiry<=dateAfter(0))error='اختر تاريخ انتهاء جديدًا بعد اليوم.';if(error){$('#form-error').textContent=error;return;}if(kind==='renew'){initial.history=initial.history||[];initial.history.push({expiry:initial.expiry,renewedAt:new Date().toISOString()});initial.expiry=v.expiry;}else{v.id=v.id||crypto.randomUUID();if(kind==='leaves')Object.assign(v,{created:Date.now(),status:'بانتظار الاعتماد'});if(kind==='tasks')v.status='جديدة';if(kind==='sales'){v.target=Number(v.target);v.actual=Number(v.actual);}db[kind].push(v);}const saved=await save();$('#dialog').close();render();if(saved)toast('تم الحفظ في النسخة التجريبية');};$('#dialog').showModal();}
$('#primary').onclick=()=>openForm(page==='overview'?'employees':page);$('#close').onclick=$('#cancel').onclick=()=>$('#dialog').close();
$('#content').addEventListener('click',async e=>{if(window.serverSaveBusy)return;let b=e.target.closest('button');if(!b)return;if(b.dataset.renew)openForm('renew',b.dataset.renew);if(b.dataset.leave){let l=db.leaves.find(x=>x.id===b.dataset.leave);if(l.status!=='بانتظار الاعتماد')return;l.status=b.dataset.decision;l.decidedAt=new Date().toISOString();l.decidedBy='مدير تجريبي';const saved=await save();render();if(saved)toast('سُجّل القرار التجريبي');}if(b.dataset.task){let t=db.tasks.find(x=>x.id===b.dataset.task);t.status=t.status==='جديدة'?'قيد التنفيذ':'مكتملة';await save();render();}});
window.addEventListener('hashchange',render);render();setInterval(()=>{if(!document.body.classList.contains('gateway')&&!$('#dialog').open&&['overview','leaves'].includes(page))render();},60000);
