'use strict';
pages.reports=['التقارير','تقارير الشركة المحددة مع تصفية وتصدير وطباعة.','تصدير'];
pages.notifications=['الإشعارات','آخر المستجدات والطلبات ومواعيد التجديد.','الإشعارات'];
pages.telegram=['ربط تلجرام','خطوات إعداد قناة التنبيهات للمدير.','الربط'];
const brandedRender=render, employeeForm=openForm, persistCompany=save;
const brandFor=c=>c===companies[1]?{name:'شركة أنيستيزيا',logo:'assets/anesthesia.png',theme:'anesthesia',label:'ANESTHESI DREAM'}:{name:'مؤسسة فايز المحيا للتجارة',logo:'assets/almohia.png',theme:'forever',label:'FOREVER52'};
const fingerprints=()=>Object.fromEntries(companies.map(c=>[c,Object.fromEntries(['employees','leaves','docs','cars','sales','tasks','uploads'].map(k=>[k,new Map((stores[c][k]||[]).map(r=>[r.id,JSON.stringify(r)]))]))]));
let previousRecords=fingerprints();
function collectChanges(){for(const c of companies){const data=stores[c];data.notifications=data.notifications||[];const labels={employees:'ملف موظف',leaves:'طلب إجازة',docs:'وثيقة',cars:'سيارة',sales:'سجل مبيعات',tasks:'مهمة تسويق',uploads:'مرفق موظف'};for(const k of Object.keys(labels))for(const r of data[k]||[]){const old=previousRecords[c][k].get(r.id);if(old===JSON.stringify(r))continue;let employeeId=r.employeeId||data.employees.find(e=>e.name===(r.employee||r.assignee))?.id;data.notifications.unshift({id:crypto.randomUUID(),time:new Date().toISOString(),title:(old?'تحديث ':'إضافة ')+labels[k],detail:r.name||r.title||r.employee||r.description||r.supervisor||r.plate||'',route:k==='uploads'?'employees':k,employeeId:employeeId||null,adminOnly:!['leaves','tasks','uploads'].includes(k)});}data.notifications=data.notifications.slice(0,300);}}
save=async function(){collectChanges();const ok=await persistCompany();if(ok)previousRecords=fingerprints();return ok;};
function notificationList(){if(!account||!db)return[];const admin=account.role==='admin';let list=(db.notifications||[]).filter(n=>admin||(!n.adminOnly&&n.employeeId===account.id));if(window.SERVER_MODE)return list;if(admin){list=[...alerts().map(a=>({id:'expiry:'+a.name+':'+a.expiry,title:days(a.expiry)<0?'وثيقة منتهية':'موعد تجديد قريب',detail:a.name+' · '+a.expiry,route:'docs',time:a.expiry+'T00:00:00Z'})),...list];}for(const l of db.leaves.filter(escalated)){if(admin||l.employeeId===account.id||(!l.employeeId&&l.employee===employee().name))list.unshift({id:'escalation:'+l.id,title:'طلب تجاوز مهلة الاعتماد',detail:l.employee+' · '+l.start,route:admin?'leaves':'profile',time:new Date(l.created+48*3600000).toISOString()});}return list;}
function readKey(){return account.role==='admin'?'admin':'employee:'+account.id;}
function unreadCount(){const reads=db.notificationReads?.[readKey()]||[];return notificationList().filter(n=>!reads.includes(n.id)).length;}
function renderNotifications(){const notes=notificationList(),reads=db.notificationReads?.[readKey()]||[];$('#content').innerHTML=panel('مركز الإشعارات',`<div class="panel-body"><div class="notification-tools"><span>${notes.length} إشعار · ${unreadCount()} غير مقروء</span><button class="secondary" id="mark-read">تحديد الكل كمقروء</button></div>${notes.map(n=>`<a class="notification-item ${reads.includes(n.id)?'read':''}" href="#${account.role==='admin'?n.route:(n.route==='tasks'?'tasks':'profile')}"><div><strong>${esc(n.title)}</strong><p>${esc(n.detail)}</p><small>${esc(n.time.slice(0,10))}</small></div>${reads.includes(n.id)?badge('مقروء'):badge('جديد','warn')}</a>`).join('')||'<p class="empty">لا توجد إشعارات جديدة للشركة أو الحساب المحدد.</p>'}</div>`);$('#mark-read').onclick=async()=>{db.notificationReads=db.notificationReads||{};db.notificationReads[readKey()]=notes.map(n=>n.id);if(await save())render();};}
function reportRows(kind,from,to){const within=date=>(!from||date>=from)&&(!to||date<=to);if(kind==='employees')return {headers:['الرقم الوظيفي','الاسم','الفرع','الإدارة','المسمى','نمط العمل'],rows:db.employees.map(e=>[e.id,e.name,e.branch,e.dept,e.job,e.mode])};if(kind==='leaves')return {headers:['الموظف','النوع','من','إلى','الحالة'],rows:db.leaves.filter(l=>(!from||l.end>=from)&&(!to||l.start<=to)).map(l=>[l.employee,l.type,l.start,l.end,escalated(l)?'مصعّد للمدير الأعلى':l.status])};if(kind==='docs')return {headers:['الوثيقة','النوع','رقم الوثيقة','الانتهاء','الأيام المتبقية'],rows:db.docs.filter(d=>!from&&!to||d.expiry&&within(d.expiry)).map(d=>[d.name,d.kind,d.number,d.expiry||'بلا تاريخ',days(d.expiry)??'—'])};if(kind==='sales')return {headers:['المشرف','الشهر','الهدف','المبيعات','الإنجاز %'],rows:db.sales.filter(s=>(!from||s.period>=from.slice(0,7))&&(!to||s.period<=to.slice(0,7))).map(s=>[s.supervisor,s.period,s.target,s.actual,Math.round(s.actual/s.target*100)])};return {headers:['اللوحة','المستلم','الاستمارة','التأمين','الفحص'],rows:db.cars.filter(c=>!from&&!to||['registration','insurance','inspection'].some(k=>c[k]&&within(c[k]))).map(c=>[c.plate,c.holder,c.registration,c.insurance,c.inspection])};}
function csvCell(value){let s=String(value??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function renderReports(){let current;$('#content').innerHTML=`<div class="toolbar"><label>نوع التقرير<select id="report-kind"><option value="employees">الموظفون</option><option value="leaves">الإجازات</option><option value="docs">الوثائق</option><option value="cars">السيارات</option><option value="sales">المبيعات</option></select></label><label>من تاريخ<input type="date" id="report-from"></label><label>إلى تاريخ<input type="date" id="report-to"></label></div><div class="report-actions"><button id="report-export" class="primary">تنزيل CSV لـ Excel</button><button id="report-print" class="secondary">طباعة / حفظ PDF</button></div><p class="private-note" id="report-help"></p><div id="report-result"></div>`;const refresh=()=>{let k=$('#report-kind').value,from=$('#report-from').value,to=$('#report-to').value;$('#report-from').disabled=$('#report-to').disabled=k==='employees';if(from&&to&&from>to&&k!=='employees'){current=null;$('#report-result').textContent='تاريخ النهاية يسبق البداية.';return;}current=reportRows(k,k==='employees'?'':from,k==='employees'?'':to);$('#report-help').textContent=k==='employees'?'قائمة الموظفين الحالية؛ لا تنطبق عليها تصفية التاريخ.':'الإجازات: تداخل الفترة. الوثائق والسيارات: موعد الانتهاء. المبيعات: شهر السجل.';$('#report-result').innerHTML=panel(esc(brandFor(selectedCompany).name)+' · '+current.rows.length+' سجل',table(current.headers,current.rows.map(r=>'<tr>'+r.map(v=>`<td>${esc(v)}</td>`).join('')+'</tr>')));};['#report-kind','#report-from','#report-to'].forEach(s=>$(s).onchange=refresh);refresh();$('#report-export').onclick=()=>{if(!current)return;const csv='\uFEFF'+[current.headers,...current.rows].map(r=>r.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`${brandFor(selectedCompany).theme}-${$('#report-kind').value}-${dateAfter(0)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('#report-print').onclick=()=>window.print();}
function renderTelegram(){$('#content').innerHTML=panel('إعداد تنبيهات تلجرام',`<div class="panel-body"><div class="notice">${badge('غير متصل','warn')} كود الإرسال جاهز ضمن ملفات الخادم. لم يربط البوت أو نظام الجدولة بعد.</div><ol class="setup-steps"><li>افتح <a href="https://t.me/BotFather" target="_blank" rel="noopener">BotFather الرسمي</a> وأرسل <code>/newbot</code> ثم اختر اسم البوت.</li><li>احتفظ بمفتاح البوت في إعدادات الخادم فقط. لا تضفه إلى GitHub أو ملفات الواجهة.</li><li>افتح محادثتك مع البوت الجديد واضغط Start.</li><li>بعد تجهيز الخادم، شغّل أداة استخراج معرف المحادثة الموجودة في <code>server/chat-id.mjs</code>.</li><li>حدد معرف محادثتك ورابط البوابة في متغيرات الخادم، ثم أرسل رسالة اختبار يدويًا من الخادم.</li><li>نربط طلبات الإجازات وتجديد الوثائق بطابور الإرسال وقاعدة البيانات، ثم نشغّل مهمة دورية للتذكيرات.</li></ol><h2>ما سيصلك بعد الربط</h2><p>إشعار مختصر بالطلب أو موعد التجديد، واسم الشركة ورابط الدخول. التفاصيل والمرفقات تبقى داخل المنصة.</p><p class="private-note">رفع الواجهة إلى GitHub وحده لا يشغّل تنبيهات تلجرام. تعليمات التنفيذ بالتفصيل في ملف SETUP-AR.md المرفق.</p></div>`);}
render=function(){brandedRender();if(!account||!selectedCompany||document.body.classList.contains('gateway'))return;const b=brandFor(selectedCompany);document.body.dataset.brand=b.theme;document.querySelector('.brand').innerHTML=`<img class="sidebar-logo" src="${b.logo}" alt="شعار ${esc(b.name)}"><div>${esc(b.name)}<small>${b.label}</small></div>`;let bell=$('#notification-bell');if(!bell){document.querySelector('.shell > header').insertAdjacentHTML('beforeend','<a id="notification-bell" class="bell-button" href="#notifications"></a>');bell=$('#notification-bell');}bell.innerHTML=`<svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg> الإشعارات <b>${unreadCount()}</b>`;bell.setAttribute('aria-label','الإشعارات، '+unreadCount()+' غير مقروء');if(['reports','notifications','telegram'].includes(page)){$('#primary').style.display='none';if(page==='notifications')renderNotifications();else if(account.role==='admin'&&page==='reports')renderReports();else if(account.role==='admin'&&page==='telegram')renderTelegram();}document.querySelectorAll('.company-banner b').forEach(e=>e.textContent=b.name);};
openForm=function(kind,id){employeeForm(kind,id);if(kind!=='employees'||account?.role!=='admin')return;$('#fields').insertAdjacentHTML('afterbegin','<div class="wide bulk-entry"><b>إضافة مجموعة موظفين</b><p>ارفع Excel بدل إدخال الموظفين واحدًا واحدًا. ستراجع البيانات قبل اعتمادها.</p><label>إرفاق ملف الموظفين<input id="bulk-employees" type="file" accept=".xlsx,.csv"></label><span>أو أكمل الحقول أدناه لإضافة موظف واحد.</span></div>');$('#bulk-employees').onchange=async()=>{const file=$('#bulk-employees').files[0];if(!file)return;$('#dialog').close();history.replaceState(null,'','#import');render();$('#import-kind').value='employees';$('#import-kind').onchange();const transfer=new DataTransfer();transfer.items.add(file);$('#import-file').files=transfer.files;await $('#import-file').onchange();};};
window.removeEventListener('hashchange',brandedRender);window.addEventListener('hashchange',render);render();
