// Read plain CSV and standard, unencrypted XLSX locally. No file is uploaded.
async function readWorkbook(file){
 if(file.size>5*1024*1024)throw Error('الحد الأقصى للملف 5 ميجابايت.');
 if(/\.csv$/i.test(file.name))return parseCSV((await file.text()).replace(/^\uFEFF/,''));
 if(!/\.xlsx$/i.test(file.name))throw Error('استخدم ملف XLSX أو CSV. ملفات XLS القديمة غير مدعومة.');
 const bytes=new Uint8Array(await file.arrayBuffer()),view=new DataView(bytes.buffer),decoder=new TextDecoder();let end=-1;
 for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){end=i;break;}
 if(end<0)throw Error('ملف Excel غير صالح.');let pos=view.getUint32(end+16,true),count=view.getUint16(end+10,true),entries=new Map(),total=0;
 if(count>2000)throw Error('الملف يحتوي على عناصر أكثر من الحد المدعوم.');
 for(let i=0;i<count;i++){if(view.getUint32(pos,true)!==0x02014b50)throw Error('تعذر قراءة بنية الملف.');let flags=view.getUint16(pos+8,true),method=view.getUint16(pos+10,true),size=view.getUint32(pos+20,true),expanded=view.getUint32(pos+24,true),n=view.getUint16(pos+28,true),extra=view.getUint16(pos+30,true),comment=view.getUint16(pos+32,true),offset=view.getUint32(pos+42,true);total+=expanded;if(total>30*1024*1024||flags&1)throw Error('ملف كبير بعد فك الضغط أو محمي بكلمة مرور.');entries.set(decoder.decode(bytes.slice(pos+46,pos+46+n)),{method,size,offset});pos+=46+n+extra+comment;}
 async function xml(name,optional=false){let e=entries.get(name);if(!e){if(optional)return null;throw Error('جزء مطلوب غير موجود في الملف: '+name);}let start=e.offset+30+view.getUint16(e.offset+26,true)+view.getUint16(e.offset+28,true),chunk=bytes.slice(start,start+e.size);if(e.method===8){try{chunk=new Uint8Array(await new Response(new Blob([chunk]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).arrayBuffer());}catch{throw Error('تعذر فك ملف XLSX. جرّب متصفحًا حديثًا أو احفظ الملف بصيغة CSV.');}}else if(e.method!==0)throw Error('ضغط الملف غير مدعوم.');let doc=new DOMParser().parseFromString(decoder.decode(chunk),'application/xml');if(doc.querySelector('parsererror'))throw Error('محتوى Excel غير صالح.');return doc;}
 let book=await xml('xl/workbook.xml'),rels=await xml('xl/_rels/workbook.xml.rels'),shared=await xml('xl/sharedStrings.xml',true);let sheet=book.getElementsByTagName('sheet')[0];if(!sheet)throw Error('الملف لا يحتوي على أوراق.');let rid=sheet.getAttribute('r:id'),rel=Array.from(rels.getElementsByTagName('Relationship')).find(r=>r.getAttribute('Id')===rid);if(!rel)throw Error('تعذر تحديد الورقة الأولى.');let target=rel.getAttribute('Target'),path=target.startsWith('/')?target.slice(1):'xl/'+target;path=path.replace('xl/./','xl/');if(path.includes('..'))throw Error('مسار ورقة غير مدعوم.');let doc=await xml(path),strings=shared?Array.from(shared.getElementsByTagName('si')).map(s=>Array.from(s.getElementsByTagName('t')).map(t=>t.textContent).join('')):[];
 let rows=Array.from(doc.getElementsByTagName('row'));if(rows.length>1001)throw Error('الحد الأقصى 1000 سجل.');return rows.map(row=>{let values=[];for(let c of row.getElementsByTagName('c')){let letters=(c.getAttribute('r')||'A').replace(/[0-9]/g,''),col=0;for(let ch of letters)col=col*26+ch.charCodeAt(0)-64;if(col>100)throw Error('عدد الأعمدة أكبر من الحد المدعوم.');if(c.getElementsByTagName('f').length)throw Error('استبدل المعادلات بقيم ثابتة قبل الاستيراد.');let v=c.getElementsByTagName('v')[0]?.textContent||'',type=c.getAttribute('t');values[col-1]=type==='s'?strings[Number(v)]||'':type==='inlineStr'?Array.from(c.getElementsByTagName('t')).map(t=>t.textContent).join(''):v;}return values;});
}
function parseCSV(text){let rows=[],row=[],cell='',quoted=false;let sep=text.split(/\r?\n/)[0].includes(';')?';':',';for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===sep&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('علامات اقتباس غير مكتملة في CSV.');if(cell||row.length){row.push(cell);rows.push(row);}if(rows.length>1001)throw Error('الحد الأقصى 1000 سجل.');return rows;}
