const dashboardRender=render,baseOpenForm=openForm;let account=null,selectedCompany=null,stores={};
const STORE='group-companies-v2';try{stores=JSON.parse(localStorage.getItem(STORE))||{};}catch{}
for(let c of companies){if(!stores[c]){let names=db.employees.filter(e=>e.company===c).map(e=>e.name);stores[c]={};for(let k of ['employees','docs','cars','sales'])stores[c][k]=db[k].filter(e=>e.company===c);stores[c].leaves=db.leaves.filter(l=>names.includes(l.employee));stores[c].tasks=db.tasks.filter(t=>names.includes(t.assignee));stores[c].uploads=[];}}
save=function(){try{localStorage.setItem(STORE,JSON.stringify(stores));return true;}catch{toast('تعذر الحفظ المحلي؛ قد تكون مساحة المتصفح ممتلئة.');return false;}};
pages.import=['استيراد البيانات','ارفع ملفك وراجع السجلات قبل إضافتها للشركة المحددة.','استيراد'];
pages.profile=['ملفي الوظيفي','بياناتك الوظيفية وطلباتك ومرفقاتك في مكان واحد.','طلب إجازة'];
pages.accounts=['حسابات الموظفين','ربط الهوية بالموظف وإصدار رمز لاختيار كلمة مروره.','حسابات'];
function gate(content){document.body.classList.add('gateway');$('#gateway').innerHTML=`<div class="gate-wrap"><div class="gate-top"><b>بوابة المجموعة</b><a href="index.html">العودة لموقع الشركة ←</a></div>${content}</div>`;}
const access = new LocalAccounts(localStorage, window.LOCAL_ADMIN_BOOTSTRAP, (company, id) => Boolean(stores[company]?.employees.some(e => e.id === id)));
let authBusy = false;
function loginView(){
  authBusy = false;
  const activating = location.hash === '#activate';
  gate(`<div class="gate-intro"><p class="eyebrow">أهلًا بك في بوابة الموظفين</p><h1>مساحتك للعمل والمتابعة</h1><p>ملفك الوظيفي، طلباتك، ومهامك.</p></div><form class="login-card" id="credential-login"><h2>${activating?'تفعيل حساب الموظف':'تسجيل الدخول'}</h2><p class="auth-caption">${activating?'استخدم رمز التفعيل الذي وفرته لك الموارد البشرية واختر كلمة مرورك.':'أدخل رقم الهوية أو الإقامة وكلمة المرور.'}</p><label for="identity">رقم الهوية أو الإقامة<input id="identity" name="identity" type="text" inputmode="numeric" autocomplete="username" maxlength="10" minlength="10" required dir="ltr" placeholder="رقم الهوية / الإقامة"></label>${activating?'<label for="activation-code">رمز التفعيل<input id="activation-code" name="code" required autocomplete="off" maxlength="16" dir="ltr"></label>':''}<label for="password">${activating?'كلمة المرور الجديدة':'كلمة المرور'}<input id="password" name="password" type="password" autocomplete="${activating?'new-password':'current-password'}" ${activating?'minlength="10"':''} maxlength="128" required dir="ltr" placeholder="أدخل كلمة المرور"></label>${activating?'<label for="password-confirm">تأكيد كلمة المرور<input id="password-confirm" name="confirmation" type="password" autocomplete="new-password" required maxlength="128" dir="ltr"></label>':''}<p id="auth-error" class="auth-error" role="alert"></p><button id="auth-submit" class="primary">${activating?'تفعيل الحساب':'تسجيل الدخول ←'}</button><a class="auth-switch" href="${activating?'#login':'#activate'}">${activating?'العودة لتسجيل الدخول':'أول دخول؟ فعّل حسابك'}</a><p class="auth-local">نسخة محلية للتجربة. الحسابات لا تتزامن بين الأجهزة حتى ربط الخدمة.</p></form>`);
  $('#credential-login').onsubmit = async event => {
    event.preventDefault();
    if (authBusy) return;
    const form = event.currentTarget, button = $('#auth-submit'), error = $('#auth-error');
    error.textContent = '';
    if (!access.validIdentity(form.elements.identity.value)) { error.textContent='أدخل رقم هوية أو إقامة من 10 أرقام يبدأ بـ 1 أو 2.'; return; }
    authBusy = true; button.disabled = true; button.textContent='جارٍ التحقق…';
    try {
      if (!globalThis.crypto?.subtle) throw Error('يلزم متصفح حديث يدعم التحقق المحلي من كلمات المرور.');
      if (activating) {
        if (form.elements.password.value !== form.elements.confirmation.value) throw Error('كلمتا المرور غير متطابقتين.');
        await access.activate(form.elements.identity.value, form.elements.code.value, form.elements.password.value);
        form.reset(); location.hash='login'; render(); toast('تم تفعيل حسابك. سجّل الدخول بكلمة مرورك الجديدة.');
      } else {
        const result = await access.login(form.elements.identity.value, form.elements.password.value);
        if (!result) throw Error('رقم الهوية أو كلمة المرور غير صحيحة، أو الحساب لم يُفعّل بعد.');
        form.reset(); enterAccount(result);
      }
    } catch (err) { error.textContent = err.name === 'QuotaExceededError'?'تعذر حفظ الحساب؛ مساحة المتصفح ممتلئة.':err.message; }
    finally { authBusy=false; button.disabled=false; button.textContent=activating?'تفعيل الحساب':'تسجيل الدخول ←'; }
  };
}
function enterAccount(result) {
  account = result;
  if (result.role === 'admin') { selectedCompany=null; location.hash='companies'; }
  else { selectedCompany=result.company; db=stores[selectedCompany]; location.hash='profile'; }
  render();
}
function renderAccounts() {
  let records;
  try { records=access.read(); } catch { $('#content').innerHTML='<div class="notice">تعذر قراءة الحسابات المحلية.</div>'; return; }
  $('#content').innerHTML=`<div class="notice">اختر الموظف وسجّل هويته لإصدار رمز تفعيل. الموظف يختار كلمة مروره بنفسه من «أول دخول؟ فعّل حسابك». في هذه التجربة يتم التفعيل والدخول على المتصفح والجهاز نفسيهما.</div>${panel('حسابات '+esc(selectedCompany),table(['الموظف','الرقم الوظيفي','الحساب','الإجراء'],db.employees.map(e=>{let r=records.find(r=>r.company===selectedCompany&&r.employeeId===e.id);return `<tr><td>${esc(e.name)}</td><td>${esc(e.id)}</td><td>${badge(r?.passwordHash?'مفعّل':r?'بانتظار التفعيل':'غير مرتبط',r?.passwordHash?'good':'')}</td><td>${r?.passwordHash?'—':`<button class="action" data-activate-employee="${esc(e.id)}">${r?'إصدار رمز جديد':'ربط الهوية وتفعيل الحساب'}</button>`}</td></tr>`;})))}`;
  document.querySelectorAll('[data-activate-employee]').forEach(button=>button.onclick=()=>{
    const person=db.employees.find(e=>e.id===button.dataset.activateEmployee);
    $('#dialog-title').textContent='تفعيل حساب '+person.name;
    $('#fields').innerHTML='<label class="wide" for="access-identity">رقم الهوية أو الإقامة<input id="access-identity" inputmode="numeric" autocomplete="off" minlength="10" maxlength="10" required dir="ltr"></label><p class="wide private-note">الرمز صالح لمدة 24 ساعة ويستخدم مرة واحدة. إصدار رمز جديد يلغي الرمز السابق غير المستخدم.</p>';
    $('#form-error').textContent='';
    const submit=$('#form button[type="submit"]');submit.textContent='إصدار رمز التفعيل';submit.disabled=false;
    let busy=false;
    $('#form').onsubmit=async event=>{
      event.preventDefault();if(busy||account?.role!=='admin')return;busy=true;submit.disabled=true;
      try {
        const code=await access.issue($('#access-identity').value,selectedCompany,person.id);
        $('#fields').innerHTML=`<div class="wide"><p>رمز تفعيل ${esc(person.name)}</p><output class="activation-code" dir="ltr">${code}</output><p class="private-note">احتفظ بهذا الرمز وأعطه للموظف. لن يظهر مرة أخرى بعد إغلاق النافذة. يستخدمه مع رقم هويته في صفحة تفعيل الحساب لاختيار كلمة مروره.</p></div>`;
        $('#form-error').textContent='';submit.textContent='تم إصدار الرمز';
        render();
      } catch(err) { $('#form-error').textContent=err.name==='QuotaExceededError'?'تعذر حفظ الحساب محليًا.':err.message;submit.disabled=false;busy=false; }
    };
    $('#dialog').showModal();
  });
}
function companyView(){gate(`<div class="gate-intro"><p class="eyebrow">${account.role==='admin'?'مساحة مدير الموارد البشرية':'بوابة الموظف'}</p><h1>اختر الشركة</h1><p>لكل شركة لوحة مستقلة بموظفيها وطلباتها وبياناتها.</p></div><div class="company-cards">${companies.filter(c=>account.role==='admin'||account.company===c).map(c=>`<button class="company-card ${c===companies[1]?'anes':''}" data-company="${esc(c)}"><div class="eyebrow">${c===companies[0]?'FOREVER52':'ANESTHESI DREAM'}</div><h2>شركة ${esc(c)}</h2><p>${account.role==='admin'?'الموظفون · الإجازات · الوثائق · المبيعات':'ملفي الوظيفي · طلباتي · مهامي'}</p><b>الدخول إلى لوحة الشركة ←</b></button>`).join('')}</div><p class="private-note">فصل البيانات هنا داخل النسخة التجريبية. الحماية الحقيقية تتطلب الحسابات وقاعدة البيانات.</p><button class="secondary" id="gate-logout">خروج</button>`);document.querySelectorAll('[data-company]').forEach(b=>b.onclick=()=>{selectedCompany=b.dataset.company;db=stores[selectedCompany];location.hash=account.role==='admin'?'overview':'profile';render();});$('#gate-logout').onclick=logoutDemo;}
function logoutDemo(){account=null;selectedCompany=null;location.hash='login';render();}
function employee(){return db.employees.find(e=>e.id===account.id);}
function profileView(){let e=employee();return `<div class="employee-help"><h2>أهلًا، ${esc(e.name)}</h2><ol><li>راجع بياناتك أدناه.</li><li>قدّم طلب إجازة وحدد الفترة ثم تابع حالته.</li><li>لإرفاق مستند، اختر الملف من قسم «مرفقاتي» ثم احفظه في التجربة.</li></ol></div>${panel('البيانات الوظيفية',`<div class="panel-body profile-grid">${[['الرقم الوظيفي',e.id],['الشركة',selectedCompany],['الفرع',e.branch],['الإدارة',e.dept],['المسمى الوظيفي',e.job],['المدير المباشر',e.manager],['نمط العمل',e.mode]].map(([k,v])=>`<div class="profile-item"><small>${k}</small><b>${esc(v||'لم يحدد')}</b></div>`).join('')}</div>`)}${panel('طلبات إجازتي',table(['النوع','الفترة','الحالة'],db.leaves.filter(l=>l.employeeId===e.id||(!l.employeeId&&l.employee===e.name)).map(l=>`<tr><td>${esc(l.type)}</td><td>${esc(l.start)} ← ${esc(l.end)}</td><td>${badge(escalated(l)?'مصعّد للمدير الأعلى':l.status)}</td></tr>`)))}${panel('مرفقاتي',`<div class="panel-body"><p class="private-note">PDF أو صورة، حتى 1 ميجابايت. تحفظ محليًا للتجربة ولا تُرسل للإدارة عبر الإنترنت.</p><form id="upload-form"><label>وصف المستند<input name="description" required maxlength="100"></label><label class="file-label">اختيار الملف<input name="file" type="file" accept="application/pdf,image/png,image/jpeg" required></label><button class="primary" style="margin-top:14px">حفظ المرفق التجريبي</button></form>${(db.uploads||[]).filter(u=>u.employeeId===e.id).map(u=>`<div class="row"><div>${esc(u.description)}<small>${esc(u.name)} · ${esc(u.date)}</small></div>${badge('محفوظ محليًا')}</div>`).join('')}</div>`)}`;}
render=function(){if(!account){loginView();return;}let route=location.hash.slice(1);const admin=account.role==='admin';if(!admin){selectedCompany=account.company;db=stores[selectedCompany];if(!employee()){logoutDemo();return;}if(!['profile','tasks','notifications'].includes(route)){location.hash='profile';route='profile';}}else if(!selectedCompany||route==='companies'){companyView();return;}document.body.classList.remove('gateway');const routes=admin?['overview','employees','accounts','leaves','docs','cars','sales','tasks','import','reports','notifications','telegram']:['profile','tasks','notifications'];$('#nav').innerHTML=routes.map(k=>`<a href="#${k}" data-page="${k}">${pages[k][0]}</a>`).join('')+(admin?'<a href="#companies">⇄ تغيير الشركة</a>':'')+'<a href="index.html">موقع الشركة ↗</a>';
document.querySelector('.brand').innerHTML=`<span class="mark">${selectedCompany===companies[0]?'F':'A'}</span><div>${selectedCompany===companies[0]?'FOREVER52':'ANESTHESI DREAM'}<small>${esc(selectedCompany)}</small></div>`;document.querySelector('.brand').href=admin?'#overview':'#profile';document.querySelector('.side-bottom').innerHTML=`<div>${admin?'مدير الموارد البشرية':esc(employee().name)}<small>${admin?'إدارة الشركة':'بوابة الموظف'}</small><button class="logout-control" id="logout-demo">تسجيل الخروج</button></div>`;$('#logout-demo').onclick=logoutDemo;
let originalTasks=db.tasks;if(!admin)db.tasks=originalTasks.filter(t=>t.employeeId?t.employeeId===account.id:t.assignee===employee().name);dashboardRender();db.tasks=originalTasks;
$('#breadcrumb').textContent=selectedCompany+' / '+pages[page][0];$('#primary').style.display=(!admin&&page==='tasks')||['import','accounts'].includes(page)?'none':'';$('#primary').onclick=()=>page==='profile'?openForm('leaves'):openForm(page==='overview'?'employees':page);
if(page==='profile'){$('#content').innerHTML=profileView();$('#upload-form').onsubmit=uploadEmployee;}
if(page==='import')renderImport();
if(page==='accounts'&&admin)renderAccounts();
if(page==='overview'){document.querySelectorAll('.stat')[3].innerHTML='<span class="stat-label">فروع الشركة في التجربة</span><strong>'+new Set(db.employees.map(e=>e.branch)).size+'</strong><small>بحسب سجلات موظفي الشركة</small>';document.querySelector('.stats .stat small').textContent='الموظفون في الشركة المحددة';let panels=document.querySelectorAll('#content > .panel');for(let p of panels)if(p.querySelector('h2')?.textContent==='شركات المجموعة')p.remove();}
$('#content').insertAdjacentHTML('afterbegin',`<div class="company-banner" style="--company-accent:${selectedCompany===companies[0]?'#d6006f':'#9c95c4'}"><b>${esc(selectedCompany)}</b><span class="muted"> · ${admin?'لوحة إدارة الشركة':'مساحة الموظف'}</span></div>`);
if(admin&&page==='employees'){$('#employee-list').insertAdjacentHTML('beforebegin','<a class="secondary" style="display:inline-block;margin-bottom:16px" href="#import">استيراد الموظفين من Excel ↑</a>');$('#content').insertAdjacentHTML('beforeend',panel('مرفقات الموظفين',table(['الموظف','المستند','اسم الملف','التاريخ','الملف'],(db.uploads||[]).map(u=>`<tr><td>${esc(db.employees.find(e=>e.id===u.employeeId)?.name||u.employeeId)}</td><td>${esc(u.description)}</td><td>${esc(u.name)}</td><td>${esc(u.date)}</td><td><button class="action" data-download="${esc(u.id)}">تنزيل</button></td></tr>`))));document.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>{let u=db.uploads.find(u=>u.id===b.dataset.download);if(!/^data:(application\/pdf|image\/(png|jpeg));base64,/.test(u.data))return toast('صيغة الملف غير صالحة.');let a=document.createElement('a');a.href=u.data;a.download=u.name;a.click();});}
};
openForm=function(kind,id){if(!account||!selectedCompany)return;if(account.role!=='admin'&&kind!=='leaves')return;const count=db.leaves.length;baseOpenForm(kind,id);$('#form button[type="submit"]').disabled=false;$('#form button[type="submit"]').textContent='حفظ';let companyInput=$('#form [name="company"]');if(companyInput){companyInput.value=selectedCompany;companyInput.disabled=true;}let empInput=$('#form [name="employee"]');if(empInput&&account.role!=='admin'){empInput.value=employee().name;empInput.disabled=true;}let submit=$('#form').onsubmit;$('#form').onsubmit=async e=>{if(companyInput)companyInput.disabled=false;if(empInput)empInput.disabled=false;await submit(e);if(companyInput)companyInput.disabled=true;if(empInput)empInput.disabled=account.role!=='admin';if(!window.SERVER_MODE&&db.leaves.length>count&&account.role!=='admin'){db.leaves.at(-1).employeeId=account.id;await save();}};};
async function uploadEmployee(event){event.preventDefault();let form=event.target,file=form.elements.file.files[0];if(!file||!['application/pdf','image/png','image/jpeg'].includes(file.type)||file.size>1024*1024)return toast('اختر PDF أو PNG أو JPG بحجم لا يزيد على 1 ميجابايت.');let bytes=new Uint8Array(await file.arrayBuffer()),sig=String.fromCharCode(...bytes.slice(0,5));if(!(file.type==='application/pdf'&&sig==='%PDF-'||file.type==='image/png'&&bytes[0]===137&&bytes[1]===80||file.type==='image/jpeg'&&bytes[0]===255&&bytes[1]===216))return toast('محتوى الملف لا يطابق نوعه.');let data=await new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});db.uploads=db.uploads||[];db.uploads.push({id:crypto.randomUUID(),employeeId:account.id,description:form.elements.description.value.trim(),name:file.name,date:dateAfter(0),data});if(!await save()){if(!window.SERVER_MODE)db.uploads.pop();return;}render();toast('حُفظ المرفق محليًا');}
const schemas={employees:{label:'الموظفون',fields:{'الرقم الوظيفي':'id','الاسم':'name','الفرع':'branch','الإدارة':'dept','المسمى الوظيفي':'job','نمط العمل':'mode','المدير المباشر':'manager'}},docs:{label:'الوثائق',fields:{'اسم الوثيقة':'name','النوع':'kind','رقم الوثيقة':'number','تاريخ الانتهاء':'expiry','ملاحظات':'notes'}},sales:{label:'المبيعات',fields:{'المشرف':'supervisor','الشهر':'period','الهدف':'target','المبيعات':'actual'}}};
function renderImport(){let pending=null;$('#content').innerHTML=panel('استيراد ملف Excel',`<div class="panel-body"><p class="import-help">1. اختر نوع البيانات. 2. استخدم أسماء الأعمدة الموضحة. 3. ارفع الملف وراجع المعاينة. 4. اعتمد الإضافة.<br>تقرأ الورقة الأولى فقط من XLSX أو CSV. حد الملف 5 ميجابايت و1000 سجل. تحفظ السجلات في <b>${esc(selectedCompany)}</b> فقط، دون تعديل السجلات الحالية.</p><div class="import-actions"><label>نوع البيانات<select id="import-kind">${Object.entries(schemas).map(([k,s])=>`<option value="${k}">${s.label}</option>`).join('')}</select></label><label>الملف<input id="import-file" type="file" accept=".xlsx,.csv"></label></div><div id="column-help" class="notice"></div><p class="private-note">اكتب الأرقام الوظيفية كنص للحفاظ على الأصفار. التواريخ YYYY-MM-DD والشهر YYYY-MM. القيم ثابتة دون معادلات. لا تضع بيانات حقيقية في هذه النسخة.</p><div id="import-preview"></div><button class="primary" id="import-confirm" disabled>اعتماد إضافة السجلات</button></div>`);
const updateHelp=()=>{$('#column-help').textContent='الأعمدة المطلوبة: '+Object.keys(schemas[$('#import-kind').value].fields).join('، ');pending=null;$('#import-confirm').disabled=true;$('#import-preview').innerHTML='';$('#import-file').value='';};$('#import-kind').onchange=updateHelp;updateHelp();
$('#import-file').onchange=async()=>{pending=null;$('#import-confirm').disabled=true;let file=$('#import-file').files[0],kind=$('#import-kind').value;if(!file)return;$('#import-preview').textContent='جارٍ قراءة الملف…';try{let rows=await readWorkbook(file);if(!rows.length)throw Error('الملف فارغ.');let schema=schemas[kind],headers=rows.shift().map(v=>String(v||'').trim()),required=Object.keys(schema.fields);if(new Set(headers).size!==headers.length)throw Error('توجد أسماء أعمدة مكررة.');let missing=required.filter(h=>!headers.includes(h));if(missing.length)throw Error('أعمدة غير موجودة: '+missing.join('، '));let errors=[],seen=new Set(),records=[];rows.forEach((r,index)=>{if(!r.some(v=>String(v??'').trim()))return;let v={};for(let h of required)v[schema.fields[h]]=String(r[headers.indexOf(h)]??'').trim();let err='';if(kind==='employees'){if(Object.values(v).some(x=>!x))err='أكمل جميع الحقول';else if(!branches.includes(v.branch))err='الفرع غير مطابق: '+branches.join(' / ');else if(!['مكتبي','ميداني'].includes(v.mode))err='نمط العمل مكتبي أو ميداني';else if(seen.has(v.id)||db.employees.some(e=>e.id===v.id))err='رقم وظيفي مكرر';seen.add(v.id);}if(kind==='docs'){if(!v.name||!v.kind)err='اسم الوثيقة ونوعها مطلوبان';if(v.expiry&&(!/^\d{4}-\d{2}-\d{2}$/.test(v.expiry)||Number.isNaN(Date.parse(v.expiry))||new Date(v.expiry).toISOString().slice(0,10)!==v.expiry))err='تاريخ الانتهاء غير صالح؛ استخدم YYYY-MM-DD';}if(kind==='sales'){v.target=Number(v.target);v.actual=Number(v.actual);if(!v.supervisor||!/^\d{4}-(0[1-9]|1[0-2])$/.test(v.period)||!(v.target>0)||!Number.isFinite(v.target)||!Number.isFinite(v.actual)||v.actual<0)err='تحقق من المشرف والشهر والأرقام';}if(err)errors.push('الصف '+(index+2)+': '+err);v.company=selectedCompany;records.push(v);});if(!records.length)throw Error('لا توجد سجلات في الملف.');if($('#import-kind').value!==kind)return;$('#import-preview').innerHTML=(errors.length?`<div class="import-errors">${errors.map(esc).join('<br>')}</div>`:`<div class="notice">${records.length} سجل جاهز للإضافة إلى ${esc(selectedCompany)}. تعرض المعاينة أول 20 سجلًا.</div>`)+table(required,records.slice(0,20).map(v=>'<tr>'+Object.values(schema.fields).map(k=>`<td>${esc(v[k])}</td>`).join('')+'</tr>'));if(!errors.length){pending={kind,records};$('#import-confirm').disabled=false;}}catch(err){$('#import-preview').textContent=err.message;}};
$('#import-confirm').onclick=async()=>{if(!pending)return;let {kind,records}=pending,oldLength=db[kind].length;records.forEach(v=>db[kind].push({...v,id:v.id||crypto.randomUUID()}));if(!await save()){if(!window.SERVER_MODE)db[kind].splice(oldLength);return;}pending=null;$('#import-confirm').disabled=true;$('#import-preview').innerHTML=`<div class="notice">تمت إضافة ${records.length} سجل إلى ${esc(selectedCompany)} بنجاح.</div>`;toast('تم الاستيراد المحلي');};}
window.removeEventListener('hashchange',dashboardRender);window.addEventListener('hashchange',render);render();
