import {createHash,randomBytes,pbkdf2,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';
import {readFileSync} from 'node:fs';
import {COMPANIES,KINDS,companyData,transaction} from './database.mjs';
import {fail,validateData,employeeView,mergeEmployeeChange} from './validation.mjs';
import {sendTelegram} from './telegram.mjs';
const derive=promisify(pbkdf2),hash=v=>createHash('sha256').update(v).digest('hex'),random=()=>randomBytes(32).toString('hex');
const identity=v=>String(v||'').trim().replace(/[٠-٩]/g,c=>c.charCodeAt(0)-1632).replace(/[۰-۹]/g,c=>c.charCodeAt(0)-1776);
const publicUser=u=>({role:u.role,...(u.role==='employee'?{company:u.company,id:u.employee_id}:{})});
const same=(a,b)=>{const x=Buffer.from(a||'','hex'),y=Buffer.from(b||'','hex');return x.length===y.length&&timingSafeEqual(x,y);};
export class Service{
 constructor(db,{bootstrapPath,telegramEnabled=false,telegramOptions={}}={}){this.db=db;this.telegramEnabled=telegramEnabled;this.telegramOptions=telegramOptions;this.busy=false;
  if(bootstrapPath&&!db.prepare("SELECT 1 FROM users WHERE role='admin'").get()){
   const source=readFileSync(bootstrapPath,'utf8'),match=source.match(/window\.LOCAL_ADMIN_BOOTSTRAP\s*=\s*(\{[^;]+\});/);if(!match)throw Error('Invalid local administrator bootstrap');const b=JSON.parse(match[1]);
   if(!/^[a-f0-9]{64}$/.test(b.identityHash)||!/^[a-f0-9]{64}$/.test(b.passwordHash)||!b.salt||!Number.isInteger(b.iterations))throw Error('Invalid administrator verifier');
   db.prepare('INSERT INTO users(identity_hash,role,salt,password_hash,iterations) VALUES(?,?,?,?,?)').run(b.identityHash,'admin',b.salt,b.passwordHash,b.iterations);
  }
 }
 userRecord(user){if(user.role==='employee'&&!this.db.prepare("SELECT 1 FROM records WHERE company=? AND kind='employees' AND id=?").get(user.company,user.employee_id))fail('الحساب غير نشط.',401);return user;}
 session(token){if(!token)return null;const s=this.db.prepare('SELECT sessions.csrf,sessions.expires,users.* FROM sessions JOIN users USING(identity_hash) WHERE sessions.hash=? AND sessions.expires>?').get(hash(token),Date.now());return s?this.userRecord(s):null;}
 async login(input){const id=identity(input.identity),password=input.password;if(!/^[12]\d{9}$/.test(id)||typeof password!=='string'||password.length>128)fail('بيانات الدخول غير صحيحة.',401);
  const u=this.db.prepare('SELECT * FROM users WHERE identity_hash=?').get(hash(id));const salt=u?.salt||'invalid-login-salt';const result=(await derive(password,salt,u?.iterations||210000,32,'sha256')).toString('hex');if(!u?.password_hash||!same(result,u.password_hash))fail('بيانات الدخول غير صحيحة أو الحساب غير مفعّل.',401);this.userRecord(u);
  const token=random(),csrf=random();this.db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(hash(token),u.identity_hash,csrf,Date.now()+8*3600000);return{token,csrf,account:publicUser(u)};
 }
 logout(token){this.db.prepare('DELETE FROM sessions WHERE hash=?').run(hash(token||''));}
 accounts(user){if(user.role!=='admin')fail('غير مسموح.',403);return this.db.prepare("SELECT company,employee_id,CASE WHEN password_hash IS NOT NULL THEN 1 ELSE 0 END AS active FROM users WHERE role='employee'").all().map(r=>({company:r.company,employeeId:r.employee_id,passwordHash:r.active?'active':null}));}
 async issue(user,input){if(user.role!=='admin')fail('غير مسموح.',403);const id=identity(input.identity);if(!/^[12]\d{9}$/.test(id)||!COMPANIES.includes(input.company)||typeof input.employeeId!=='string')fail('تحقق من الهوية والشركة.');
  if(!this.db.prepare("SELECT 1 FROM records WHERE company=? AND kind='employees' AND id=?").get(input.company,input.employeeId))fail('أضف الموظف أولًا.');const digest=hash(id),code=randomBytes(8).toString('hex').toUpperCase();
  transaction(this.db,()=>{const existing=this.db.prepare('SELECT * FROM users WHERE identity_hash=? OR (company=? AND employee_id=?)').all(digest,input.company,input.employeeId);if(existing.some(r=>r.role==='admin'||r.password_hash||r.company!==input.company||r.employee_id!==input.employeeId))fail('الحساب مفعّل أو الهوية مرتبطة بحساب آخر.');this.db.prepare('DELETE FROM users WHERE company=? AND employee_id=?').run(input.company,input.employeeId);this.db.prepare('INSERT INTO users(identity_hash,role,company,employee_id,activation_hash,activation_expires) VALUES(?,?,?,?,?,?)').run(digest,'employee',input.company,input.employeeId,hash(code),Date.now()+86400000);});return{code};
 }
 async activate(input){const id=identity(input.identity),pass=input.password;if(!/^[12]\d{9}$/.test(id)||typeof pass!=='string'||pass.length<10||pass.length>128||typeof input.code!=='string')fail('تحقق من بيانات التفعيل وطول كلمة المرور.');const digest=hash(id),code=hash(input.code.trim().toUpperCase()),u=this.db.prepare('SELECT * FROM users WHERE identity_hash=?').get(digest);if(!u||u.password_hash||u.activation_hash!==code||u.activation_expires<=Date.now())fail('رمز التفعيل غير صحيح أو منتهي.');this.userRecord(u);
  const salt=random(),passwordHash=(await derive(pass,salt,210000,32,'sha256')).toString('hex');const result=this.db.prepare('UPDATE users SET salt=?,password_hash=?,iterations=210000,activation_hash=NULL,activation_expires=NULL WHERE identity_hash=? AND activation_hash=? AND activation_expires>? AND password_hash IS NULL').run(salt,passwordHash,digest,code,Date.now());if(!result.changes)fail('رمز التفعيل لم يعد صالحًا.');return{ok:true};
 }
 snapshot(user){const stores={},revisions={};for(const c of COMPANIES.filter(c=>user.role==='admin'||c===user.company)){let data=companyData(this.db,c);if(user.role!=='admin')data=employeeView(data,user);data.notifications=this.db.prepare('SELECT * FROM notifications WHERE company=? ORDER BY time DESC LIMIT 300').all(c).filter(n=>user.role==='admin'||(!n.admin_only&&n.employee_id===user.employee_id)).map(n=>({id:n.id,title:n.title,detail:n.detail,route:n.route,employeeId:n.employee_id,adminOnly:Boolean(n.admin_only),time:n.time}));const key=user.role==='admin'?'admin':'employee:'+user.employee_id;data.notificationReads={[key]:this.db.prepare('SELECT notification_id FROM reads WHERE identity_hash=?').all(user.identity_hash).map(r=>r.notification_id)};stores[c]=data;revisions[c]=this.db.prepare('SELECT revision FROM companies WHERE name=?').get(c).revision;}return{stores,revisions,accounts:user.role==='admin'?this.accounts(user):[]};}
 notify(company,{id=random(),title,detail='',route,employeeId=null,adminOnly=true,type=null}){const time=new Date().toISOString();const added=this.db.prepare('INSERT OR IGNORE INTO notifications VALUES(?,?,?,?,?,?,?,?)').run(id,company,title,detail,route,employeeId,Number(adminOnly),time);if(added.changes&&type)this.db.prepare('INSERT OR IGNORE INTO outbox(id,body) VALUES(?,?)').run(id,JSON.stringify({id,type,company}));}
 put(user,input){const c=input.company;if(!COMPANIES.includes(c)||user.role!=='admin'&&user.company!==c)fail('غير مسموح لهذه الشركة.',403);validateData(input.data,c);
  return transaction(this.db,()=>{const revision=this.db.prepare('SELECT revision FROM companies WHERE name=?').get(c).revision;if(input.revision!==revision)fail('تغيرت البيانات من جلسة أخرى؛ حدّث البيانات وأعد المحاولة.',409);const old=companyData(this.db,c),next=user.role==='admin'?structuredClone(input.data):mergeEmployeeChange(old,input.data,user);
   for(const k of ['leaves','tasks'])for(const r of next[k]){const prior=old[k].find(x=>x.id===r.id);if(!r.employeeId){const matches=next.employees.filter(e=>e.name===(r.employee||r.assignee));if(matches.length!==1)fail('اربط الطلب أو المهمة بموظف محدد غير مكرر الاسم.');r.employeeId=matches[0].id;}if(!next.employees.some(e=>e.id===r.employeeId))fail('الموظف المرتبط بالسجل غير موجود.');if(k==='leaves'){if(!prior)r.created=Date.now();else{r.created=prior.created;if(prior.status!=='بانتظار الاعتماد'&&r.status!==prior.status)fail('لا يمكن تغيير قرار طلب محسوم.');if(prior.status!==r.status){r.decidedAt=new Date().toISOString();r.decidedBy='الإدارة';}}}}
   for(const u of next.uploads)if(!next.employees.some(e=>e.id===u.employeeId))fail('المرفق غير مرتبط بموظف.');
   const labels={employees:'ملف موظف',leaves:'طلب إجازة',docs:'وثيقة',cars:'سيارة',sales:'سجل مبيعات',tasks:'مهمة تسويق',uploads:'مرفق موظف'};
   for(const k of KINDS){const prior=new Map(old[k].map(r=>[r.id,r]));for(const r of next[k]){const before=prior.get(r.id);if(JSON.stringify(before)!==JSON.stringify(r)){this.notify(c,{title:(before?'تحديث ':'إضافة ')+labels[k],detail:r.name||r.title||r.employee||r.description||r.plate||'',route:k==='uploads'?'employees':k,employeeId:r.employeeId||null,adminOnly:!['tasks','leaves','uploads'].includes(k),type:!before?({employees:'employee_created',leaves:'leave_created',tasks:'task_created'}[k]||null):null});}}
    this.db.prepare('DELETE FROM records WHERE company=? AND kind=?').run(c,k);for(const r of next[k])this.db.prepare('INSERT INTO records VALUES(?,?,?,?)').run(c,k,r.id,JSON.stringify(r));}
   const key=user.role==='admin'?'admin':'employee:'+user.employee_id;for(const id of (input.data.notificationReads?.[key]||[]).slice(0,1000)){const n=this.db.prepare('SELECT * FROM notifications WHERE id=? AND company=?').get(id,c);if(n&&(user.role==='admin'||!n.admin_only&&n.employee_id===user.employee_id))this.db.prepare('INSERT OR IGNORE INTO reads VALUES(?,?)').run(user.identity_hash,id);}
   this.db.prepare('UPDATE companies SET revision=revision+1 WHERE name=?').run(c);this.db.prepare('INSERT INTO audit(actor,action,company,time) VALUES(?,?,?,?)').run(user.identity_hash,'save_company',c,new Date().toISOString());return this.snapshot(user);
  });
 }
 schedule(now=new Date()){
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(now),day=Date.parse(today+'T00:00:00Z');
  transaction(this.db,()=>{for(const c of COMPANIES){const data=companyData(this.db,c),docs=[...data.docs,...data.cars.flatMap(car=>['registration','insurance','inspection'].map(k=>({id:car.id+':'+k,name:'وثيقة سيارة '+car.plate,expiry:car[k]})))];for(const d of docs){if(!d.expiry)continue;const remaining=Math.round((Date.parse(d.expiry+'T00:00:00Z')-day)/86400000);const threshold=remaining<=0?0:remaining<=7?7:remaining<=30?30:remaining<=60?60:null;if(threshold===null)continue;this.notify(c,{id:'expiry:'+c+':'+d.id+':'+d.expiry+':'+threshold,title:remaining<0?'وثيقة منتهية':'تذكير بتجديد وثيقة',detail:d.name+' · '+d.expiry,route:'docs',type:'document_expiry'});}
   for(const l of data.leaves)if(l.status==='بانتظار الاعتماد'&&now.getTime()-l.created>=48*3600000)this.notify(c,{id:'escalation:'+c+':'+l.id,title:'طلب تجاوز مهلة اليومين',detail:l.employee,route:'leaves',employeeId:l.employeeId,adminOnly:false,type:'leave_escalated'});
  }this.db.prepare('DELETE FROM sessions WHERE expires<?').run(now.getTime());});
 }
 relevant(event){const data=companyData(this.db,event.company);if(event.type==='document_expiry'){const docs=[...data.docs,...data.cars.flatMap(c=>['registration','insurance','inspection'].map(k=>({id:c.id+':'+k,expiry:c[k]})))];return docs.some(d=>d.expiry&&event.id.startsWith('expiry:'+event.company+':'+d.id+':'+d.expiry+':'));}if(event.type==='leave_escalated')return data.leaves.some(l=>l.status==='بانتظار الاعتماد'&&event.id==='escalation:'+event.company+':'+l.id);return true;}
 async dispatch(){if(this.busy||!this.telegramEnabled)return;this.busy=true;try{for(let i=0;i<10;i++){const event=transaction(this.db,()=>{const row=this.db.prepare("SELECT * FROM outbox WHERE state IN ('pending','sending') AND retry_at<=? AND lease_until<=? ORDER BY rowid LIMIT 1").get(Date.now(),Date.now());if(row)this.db.prepare("UPDATE outbox SET state='sending',lease_until=? WHERE id=?").run(Date.now()+60000,row.id);return row;});if(!event)break;const payload=JSON.parse(event.body);if(!this.relevant(payload)){this.db.prepare("UPDATE outbox SET state='cancelled',lease_until=0 WHERE id=?").run(event.id);continue;}try{await sendTelegram(payload,this.telegramOptions);this.db.prepare("UPDATE outbox SET state='sent',sent_at=?,lease_until=0,error=NULL WHERE id=?").run(new Date().toISOString(),event.id);}catch(error){const delay=Math.max(error.retryAfter||60,Math.min(3600,60*2**Math.min(event.attempts,6)));this.db.prepare("UPDATE outbox SET state='pending',attempts=attempts+1,retry_at=?,lease_until=0,error=? WHERE id=?").run(Date.now()+delay*1000,error.message,event.id);}}}finally{this.busy=false;}}
 status(){return{configured:Boolean(process.env.TELEGRAM_BOT_TOKEN&&process.env.TELEGRAM_CHAT_ID),enabled:this.telegramEnabled,pending:this.db.prepare("SELECT count(*) AS n FROM outbox WHERE state IN ('pending','sending')").get().n,sent:this.db.prepare("SELECT count(*) AS n FROM outbox WHERE state='sent'").get().n};}
}
